### ISSUE TITLE
Utility type Omit is now included in the official TypeScript (since v3.5)

### ISSUE THREAD

**Issue by mjsarfatti** [typescript-cheatsheets/typescript-utilities-cheatsheet#1]
As the subject says :) Please see:

- https://www.typescriptlang.org/docs/handbook/utility-types.html#omittk
- https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-5.html#the-omit-helper-type

Question 1: Should we take it off this cheatsheet? (I can submit a PR)
Question 2: Should we point the link "Be familiar with the Utility Types that ship with TS" to the official TS handbook page on utility types, instead of a blog post, which is deemed to become stale at some point? (Again, happy to submit a PR :) )

**Comment by eps1lon** [comment]
Both suggestions sound great. I'd say go for it :+1:

**Comment by sw-yx** [comment]
awesome stuff @mjsarfatti ! when i wrote that, the ts handbook didnt have a page listing its own utility types 😂  it has come a long way since then

great work, pls let me know if you want to help maintain this repo!

**Comment by mjsarfatti** [comment]
Oh wow, it did come a long way!
I've only started using typescript a few months ago, and as I learn I often find myself referring to this cheat-sheet, which is very handy as I get a chance to verify and update bits and pieces at the same time, as you can see.
All this to say: I do want to help maintain it! My availability typically swings heavily depending on current workload, but yes, happy to help as much as possible.

**Comment by sw-yx** [comment]
invited u :)
